import { getLayout } from '@/layout'
import { Feed } from '@features/post/components/Feed'
import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Anon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed />
    </div>
  )
}

Home.getLayout = getLayout

export default Home
