import type { NextPage } from 'next'
import Head from 'next/head'
import { MainLayout } from '../src/components/layout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Aveu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <MainLayout />
      </div>
    </div>
  )
}

export default Home
