import Head from 'next/head'
import { getLayout, MainLayout } from '@layout'
import { Feed } from '@features/post/components'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Anon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed />
    </div>
  )
}

Home.Layout = MainLayout

export default Home
